# Generated by Django 3.2.9 on 2021-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves_left',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
