# Generated by Django 3.2.9 on 2021-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_moves_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
