# Generated by Django 3.2.9 on 2022-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('', 'None'), ('P', 'Player'), ('C', 'Com'), ('T', 'Tie')], max_length=1, null=True),
        ),
    ]
