# Generated by Django 3.2.9 on 2022-01-22 09:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('', 'None'), ('A', 'Player1'), ('B', 'Player2'), ('C', 'Computer'), ('T', 'Tie')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='GameP2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=3), default=games.models.default_board, size=3)),
                ('moves_left', models.PositiveSmallIntegerField(default=9)),
                ('winner', models.CharField(blank=True, choices=[('', 'None'), ('A', 'Player1'), ('B', 'Player2'), ('C', 'Computer'), ('T', 'Tie')], max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player1_symbol', models.CharField(default='X', max_length=1)),
                ('player2_symbol', models.CharField(default='O', max_length=1)),
                ('player1_wins', models.PositiveSmallIntegerField(default=0)),
                ('player2_wins', models.PositiveSmallIntegerField(default=0)),
                ('total_games', models.PositiveSmallIntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player1', 'player2')},
            },
        ),
    ]
